App_Scaffold/config/routes.rb
Rails.application.routes.draw do
  resources :buys
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "buys#index"
end

App_Scaffold/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

App_Scaffold/app/models/buy.rb
class Buy < ApplicationRecord
  validates :category, :description, :amount, presence: true
end

App_Scaffold/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

App_Scaffold/app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: %i[ show edit update destroy ]

  # GET /buys or /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1 or /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys or /buys.json
  def create
    @buy = Buy.new(buy_params)

    respond_to do |format|
      if @buy.save
        format.html { redirect_to @buy, notice: "Buy was successfully created." }
        format.json { render :show, status: :created, location: @buy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buys/1 or /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: "Buy was successfully updated." }
        format.json { render :show, status: :ok, location: @buy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1 or /buys/1.json
  def destroy
    @buy.destroy!

    respond_to do |format|
      format.html { redirect_to buys_path, status: :see_other, notice: "Buy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def buy_params
      params.require(:buy).permit(:category, :description, :amount)
    end
end

App_Scaffold/app/helpers/application_helper.rb
module ApplicationHelper
end

App_Scaffold/app/helpers/buys_helper.rb
module BuysHelper
end

App_Scaffold/app/views/buys/_buy.html.erb
<div id="<%= dom_id buy %>">
  <p>
    <strong>Category:</strong>
    <%= buy.category %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= buy.description %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= buy.amount %>
  </p>

</div>

App_Scaffold/app/views/buys/_form.html.erb
<%= form_with(model: buy) do |form| %>
  <% if buy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(buy.errors.count, "error") %> prohibited this buy from being saved:</h2>

      <ul>
        <% buy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

App_Scaffold/app/views/buys/edit.html.erb
<% content_for :title, "Editing buy" %>

<h1>Editing buy</h1>

<%= render "form", buy: @buy %>

<br>

<div>
  <%= link_to "Show this buy", @buy %> |
  <%= link_to "Back to buys", buys_path %>
</div>

App_Scaffold/app/views/buys/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Buys" %>

<h1>Buys</h1>

<div id="buys">
  <% @buys.each do |buy| %>
    <%= render buy %>
    <p>
      <%= link_to "Show this buy", buy %>
    </p>
  <% end %>
</div>

<%= link_to "New buy", new_buy_path %>

App_Scaffold/app/views/buys/new.html.erb
<% content_for :title, "New buy" %>

<h1>New buy</h1>

<%= render "form", buy: @buy %>

<br>

<div>
  <%= link_to "Back to buys", buys_path %>
</div>

App_Scaffold/app/views/buys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @buy %>

<div>
  <%= link_to "Edit this buy", edit_buy_path(@buy) %> |
  <%= link_to "Back to buys", buys_path %>

  <%= button_to "Destroy this buy", @buy, method: :delete %>
</div>

App_Scaffold/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App Scaffold" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>